# Configuración del Tema
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Icono de la pestaña (Favicon)
# Asegúrate de subir un archivo llamado favicon.png a la carpeta assets/images/
favicon: "/assets/images/icons8-desarrollador.gif"

# Plugins necesarios para que no dé error
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Información Personal
author:
  name: "Joaquín Mendoza"
  bio: "Estudiante Analista Programador"
  location: "Ñuñoa, Chile"
  avatar: "/assets/images/image-joaquin.png"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joamendozacuevas"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joaquin-mendoza-designer/" # R
# Ajustes de la página
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
