# Configuración del Tema
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Título del sitio (el que aparece arriba a la izquierda)
title: "Joaquín Mendoza"

# Plugins necesarios
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Información Personal (Barra lateral)
author:
  name: "Joaquín Mendoza"
  bio: "Estudiante Analista Programador"
  location: "Ñuñoa, Chile"
  avatar: "/assets/images/image-joaquin.png"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joamendozacuevas"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/joaquin-mendoza-designer/"

# Ajustes de la página
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
      author_profile: true
